name: msu-covid #Environment name
dependencies:
  - python=3.6
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - dash-bootstrap-components
    - pandas
    - plotly
    - typing
    - pathlib
    - xlrd
    - gunicorn # for app deployment